### ISSUE TITLE
JAS - CDDL

### ISSUE THREAD

**Issue by athiasjerome** [OpenC2-org/jaen#1]
Could JAS benefit from CCDL for simplification?
e.g. enumerations/choices
Ref. https://datatracker.ietf.org/doc/draft-greevenbosch-appsawg-cbor-cddl/?include_text=1

**Comment by davaya** [comment]
Thanks for bringing CDDL to our attention.   The slash notation for choices certainly looks attractive.  But rather than attempting to modify JAS (which is an ad-hoc tool for composing JAEN, not an essential component), I'd suggest instead a complete CDDL-to-JAEN translation, making up missing bits of CDDL and/or JAEN as necessary to achieve complete coverage.   The goal is for JAEN to be able to represent XML, JSON and CBOR schemas - if CDDL can be translated successfully to JAEN then CDDL becomes applicable to more than just CBOR, perhaps replacing JAS as the language of choice for documenting JAEN schemas.

**Comment by athiasjerome** [comment]
Makes perfect sense
